#!/bin/bash
#SBATCH --job-name='NTE_NMF'
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32GB
#SBATCH --time=2-10:00:00

srun /data/p301974/venv/bin/python3.8 -u /data/p301974/MN_IT.py